server:
  port: 8701      # 端口
eureka:
  instance:
    hostname: localhost     # host
  client:
    service-url:
      defaultZone: http://localhost:8700/eureka/      # eureka server url
spring:
  cloud:
    config:
      server:
        git:                                                            # 采用 git 仓库存储配置文件
          uri: https://github.com/wesleylien/spring_cloud_test/           # 配置git仓库地址
          searchPaths: config                                          # 配置仓库路径
          username: wesleylien                                       # 访问git仓库的用户名
          password: xdiy^Vu6K[3rpu                                       # 访问git仓库的用户密码
      label: master                                                     # 分支名，config client 亦可自己决定分支
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest