management:
  port: 8990
#spring:
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8700/eureka/      # eureka server url