spring:
  profiles:
    active: dev   # 使用的环境配置，这里如果 fail-fast: true，则读取失败的情况下，默认读取 *-dev.yml 文件
management:
  security:
    enabled: false
feign:                            # feign 开启 hystrix
  hystrix:
    enabled: true
logging:
  level:
    root: INFO
    org.springframework.web.servlet.DispatcherServlet: DEBUG